-- Generado por scripts/generate-questions-sql.mjs. No editar a mano.
-- Se pega en Supabase: SQL Editor -> New query -> Run, SIN seleccionar texto.
-- Reemplaza las preguntas de cada test y versión; se puede correr de nuevo.

create table if not exists questions (
  test_slug text not null,
  test_version text not null,
  number smallint not null,
  text text not null,
  primary key (test_slug, test_version, number)
);

-- Solo se lee desde el panel de Supabase: sin acceso con la clave pública.
alter table questions enable row level security;
revoke all on table questions from anon, authenticated;

delete from questions where test_slug = 'rotometro-original' and test_version = '1.0';
insert into questions (test_slug, test_version, number, text) values
  ('rotometro-original', '1.0', 1, 'Usa para paseos la ropa deportiva que le dieron para el campeonato interempresarial?'),
  ('rotometro-original', '1.0', 2, 'Hace fila en los puestos de degustacion de los supermercados?'),
  ('rotometro-original', '1.0', 3, 'En las fiestas familiares hacen porotos con riendas?'),
  ('rotometro-original', '1.0', 4, 'Tiene algun vecino en su cuadra que saca los parlantes a la calle?'),
  ('rotometro-original', '1.0', 5, 'Los saca Ud. mismo?'),
  ('rotometro-original', '1.0', 6, 'Compra jeans en el Persa Estacion?'),
  ('rotometro-original', '1.0', 7, 'Tiene platos o copas de Bilz y/o Pap en su casa?'),
  ('rotometro-original', '1.0', 8, 'Se sabe de memoria una cancion en ingles aunque no entiende ni jota lo que dice?'),
  ('rotometro-original', '1.0', 9, 'Manda a enmarcar el certificado de todo curso que realiza?'),
  ('rotometro-original', '1.0', 10, 'Por lo menos una vez en la vida ha organizado una "completada" bailable?'),
  ('rotometro-original', '1.0', 11, 'Cuando oye musica dice: "me fascina este tema"?'),
  ('rotometro-original', '1.0', 12, 'Su unica coleccion de CD es la de "Las Ultimas Noticias"?'),
  ('rotometro-original', '1.0', 13, 'Lleva siempre una peineta "pantera" en el bolsillo de la camisa?'),
  ('rotometro-original', '1.0', 14, 'Al vestirse cree Ud. que el cafe o el fucsia combinan con todos los colores?'),
  ('rotometro-original', '1.0', 15, 'Se pasa apagando las luces de su casa?'),
  ('rotometro-original', '1.0', 16, 'Llama "princesa", "niña", "reina" o "linda" alas mujeres que no conoce?'),
  ('rotometro-original', '1.0', 17, 'Usa Hawaianas en la casa?'),
  ('rotometro-original', '1.0', 18, 'Es Ud. de los que dice "no leí el libro, pero vi la película"?'),
  ('rotometro-original', '1.0', 19, 'Se suena la nariz en la ducha?'),
  ('rotometro-original', '1.0', 20, 'Tiene el refrigerador en el comedor?'),
  ('rotometro-original', '1.0', 21, 'Tiene el televisor en la sala?'),
  ('rotometro-original', '1.0', 22, 'Usa palillos mondadientes después del almuerzo?'),
  ('rotometro-original', '1.0', 23, 'Se pone el anillo o la medalla de graduación?'),
  ('rotometro-original', '1.0', 24, 'Se lleva en su maleta el jabón, el shampoo y el gorro de baño de los hoteles?'),
  ('rotometro-original', '1.0', 25, 'Le dice padrino a su padrino?'),
  ('rotometro-original', '1.0', 26, 'Los domingos sale a asolearse en polera tipo "rambo" a la plaza del barrio?'),
  ('rotometro-original', '1.0', 27, 'Es de los que aplaude cuando el avión aterriza?'),
  ('rotometro-original', '1.0', 28, 'Es de los que aplaude cuando termina la película?'),
  ('rotometro-original', '1.0', 29, 'Lleva a la polola al cine solamente los miércoles?'),
  ('rotometro-original', '1.0', 30, 'Guarda los frascos viejos de mermelada para usarlos como vasos?'),
  ('rotometro-original', '1.0', 31, 'Tiene un hermano que se llame Edwin o Nelson?'),
  ('rotometro-original', '1.0', 32, 'Ud. se llama Edwin o Nelson?'),
  ('rotometro-original', '1.0', 33, 'Hace pipí en la ducha?'),
  ('rotometro-original', '1.0', 34, 'Su mejor amiga se llama Jocelyn, Daisy o Jennifer?'),
  ('rotometro-original', '1.0', 35, 'Le parece buen programa "Domingo 7"?'),
  ('rotometro-original', '1.0', 36, 'Usa buzos de material sintético color neón con zapatos de vestir con taco (o mocasines de vestir)?'),
  ('rotometro-original', '1.0', 37, 'Usa hawaianas con medias cuando esta en la casa?'),
  ('rotometro-original', '1.0', 38, 'Serán por casualidad esas medias de marca "Bingo"?'),
  ('rotometro-original', '1.0', 39, 'Come arroz (o su plato de fondo) con cuchara?'),
  ('rotometro-original', '1.0', 40, 'Tiene esos llaveros de plástico para colocar las fotos "carnet" de sus familiares?'),
  ('rotometro-original', '1.0', 41, 'Tiene alfombra de peluche en el tablero del auto?'),
  ('rotometro-original', '1.0', 42, 'Tiene respaldo de reflexologia en el asiento del conductor?'),
  ('rotometro-original', '1.0', 43, 'Aplaude y/o hace barra en los restaurantescuando alguien rompe un vaso o un plato?'),
  ('rotometro-original', '1.0', 44, 'Cuando en un Bingo sale el numero 69 chifla y grita?'),
  ('rotometro-original', '1.0', 45, 'Revisa el deposito de monedas de los telefonospublicos para ver si hay sencillo?'),
  ('rotometro-original', '1.0', 46, 'Se lleva los sachets de ketchup y/o mostaza delos restaurantes de comida rapida?'),
  ('rotometro-original', '1.0', 47, 'Compra ropa de marca solamente si el nombre semuestra exteriormente y es visible a 100m de distancia?'),
  ('rotometro-original', '1.0', 48, 'Usa lentes oscuros en invierno, de noche o enlugares donde no hay luz natural?'),
  ('rotometro-original', '1.0', 49, 'Guarda sus monedas en el bolsillo dentro de un pañuelo?'),
  ('rotometro-original', '1.0', 50, 'Toma gaseosa en la casa y tapa lo que queda enla botella con un corcho?'),
  ('rotometro-original', '1.0', 51, 'Fuiste adepto(a) a la moda "marinerito" de tiendas "La Polar"?'),
  ('rotometro-original', '1.0', 52, 'Te cortas el pelo en la Galeria Imperio?'),
  ('rotometro-original', '1.0', 53, 'Tienes al menos un par de zapatos plataforma?'),
  ('rotometro-original', '1.0', 54, 'Viste ternos con manga corta o con medias blancas o con la corbata hasta la mitad del pecho?'),
  ('rotometro-original', '1.0', 55, 'Vuelve a llenar su botella de agua mineral conagua de la caneria?'),
  ('rotometro-original', '1.0', 56, 'Rellena con tecito las botellas de licores en miniatura?'),
  ('rotometro-original', '1.0', 57, 'Come un platano a medias y lo deja envuelto ensu cascara?'),
  ('rotometro-original', '1.0', 58, 'Compra comida china y guarda los recipientespara uso posterior?'),
  ('rotometro-original', '1.0', 59, 'Cuando va de paseo, prepara jugos o refrescos y los mete en botellas con tapa rosca?'),
  ('rotometro-original', '1.0', 60, 'En su epoca de colegial usaba zapatillas "Jet"de Bata?'),
  ('rotometro-original', '1.0', 61, 'Las usaba en conjunto con un short azul?'),
  ('rotometro-original', '1.0', 62, 'Tiene ud. algun buzo Nike con los cierres marca"Rey"?'),
  ('rotometro-original', '1.0', 63, 'Usa perfume Old Spice, Lancaster o Kabuki?'),
  ('rotometro-original', '1.0', 64, 'Cuelga un CD del espejo retrovisor de su auto?'),
  ('rotometro-original', '1.0', 65, 'Tiene en el tablero de su auto un perro (o leono tigre) que agita la cabeza con el movimiento?'),
  ('rotometro-original', '1.0', 66, 'Ha usado Jeans Cheldiz?'),
  ('rotometro-original', '1.0', 67, 'Cuando no conoce el nombre de alguien le dice"amigo" o "amiga"?'),
  ('rotometro-original', '1.0', 68, 'Trata de "Jefe" o de "socio" al acomodador deautos o al garzon?'),
  ('rotometro-original', '1.0', 69, 'Se compra la ropa en el "Lider" o en el "Jumbo"?'),
  ('rotometro-original', '1.0', 70, 'Le agrada esta combinacion?: medias de terno,zapatos de vestir y short? (+ 2 ptos)'),
  ('rotometro-original', '1.0', 71, 'Cuando deja esperando a alguien en el telefonole dice que lo espere "un cassshito" o un "ssshiquitito"'),
  ('rotometro-original', '1.0', 72, 'Cuando come parrillada en un restaurant pide quele envuelvan lo que sobra para llevarselo al perro?'),
  ('rotometro-original', '1.0', 73, 'Es la palanca de cambios de su auto de acrilico transparente con una mosca, jaiva o escorpion en su interior?'),
  ('rotometro-original', '1.0', 74, 'La tercera luz de frenos es de esas que seencienden en secuencia de una lado para otro, modelo "auto fantastico"?'),
  ('rotometro-original', '1.0', 75, 'Le gustan orquestas como "American Sound" o"Comanche"?'),
  ('rotometro-original', '1.0', 76, 'Encuentra seria "La Cuarta"?'),
  ('rotometro-original', '1.0', 77, 'Dice algunas de las siguientes palabras: lagana, dispertar, denantes, emprestame, rempujar. O expresiones: Ganate aca,entra p''a dentro?'),
  ('rotometro-original', '1.0', 78, 'Usa chaquetas de cuatro o mas botones, estilo "Bam-Bam" Zamorano?'),
  ('rotometro-original', '1.0', 79, 'Llama "slips" a los calzoncillos?'),
  ('rotometro-original', '1.0', 80, 'Llama "cuadros" a los calzones"?'),
  ('rotometro-original', '1.0', 81, 'Llama "sobacos" a las axilas?'),
  ('rotometro-original', '1.0', 82, 'Llama "traste" al poto?'),
  ('rotometro-original', '1.0', 83, 'Cuando se divierte Ud. dice que esta"ssshacoteando", "lesseando" O "essshando el pelo"?'),
  ('rotometro-original', '1.0', 84, 'Gusta de "sabanear" sus gases?'),
  ('rotometro-original', '1.0', 85, 'Se mete la tapa del lapiz en la oreja y despuesmira lo que saca?'),
  ('rotometro-original', '1.0', 86, 'Ha comprado zapatillas estilo NBA?'),
  ('rotometro-original', '1.0', 87, 'Las ha usado con cordones sueltos?'),
  ('rotometro-original', '1.0', 88, 'Todavia las esta pagando?'),
  ('rotometro-original', '1.0', 89, 'Cree que las botas estilo "Terminator" todavia estan a la moda?'),
  ('rotometro-original', '1.0', 90, 'Se peina con gomina y le queda el pelo parado?'),
  ('rotometro-original', '1.0', 91, 'Toma "jote" o "fanssshops"?'),
  ('rotometro-original', '1.0', 92, 'Le puso llantas "Momo" a su auto japones del ''85?'),
  ('rotometro-original', '1.0', 93, 'Escucha a la Magaly Acevedo?'),
  ('rotometro-original', '1.0', 94, 'Usa la pulsera de los "Once Poderes"?'),
  ('rotometro-original', '1.0', 95, 'Ha escuchado a Omarcito o encuentra bueno suprograma televisivo?'),
  ('rotometro-original', '1.0', 96, 'Lleva una radio con Compact Disc cuando va a la playa?'),
  ('rotometro-original', '1.0', 97, 'Cuando ocupa la parrilla del auto, la tapa con una frazada?'),
  ('rotometro-original', '1.0', 98, 'Cuando ofrece algo a una mujer que no conoce le dice: "Se sirve la dama"?'),
  ('rotometro-original', '1.0', 99, 'Encuentra "cuico" a un futbolista?'),
  ('rotometro-original', '1.0', 100, 'Le gusta Adrian y los dados negros?'),
  ('rotometro-original', '1.0', 101, 'Lo encuentra buenmozo?'),
  ('rotometro-original', '1.0', 102, 'Tiene cassetes de Adrian?'),
  ('rotometro-original', '1.0', 103, 'Cuando enfrenta una luz roja, se saca los mocos con un dedo?'),
  ('rotometro-original', '1.0', 104, 'Se deja larga la una de algun dedo menique?'),
  ('rotometro-original', '1.0', 105, 'Usa el cuchillo como tenedor y pinssha alguna cosita?'),
  ('rotometro-original', '1.0', 106, 'Luego de un opiparo almuerzo se le sale un flato en la mesa y dijo que era un hipo?'),
  ('rotometro-original', '1.0', 107, 'Tiene su vehiculo un reborde morado luminoso en la patente?'),
  ('rotometro-original', '1.0', 108, 'Su vehiculo se ilumina morado por debajo como el auto fantastico?'),
  ('rotometro-original', '1.0', 109, 'Tiene una bocina tipo vaca o un silbido tipo piropo?'),
  ('rotometro-original', '1.0', 110, 'La usa cada vez que ve pasar a una mina?'),
  ('rotometro-original', '1.0', 111, 'Tiene su vehiculo los vidrios polarizados negros y lo conduce con la radio a 90 decibeles?'),
  ('rotometro-original', '1.0', 112, 'Lo conduce con el brazo izquierdo colgando y con la tipica quemada de taxista?'),
  ('rotometro-original', '1.0', 113, 'Tiene su vehiculo la calcomania del ninito con cara de malo que hace pipi?'),
  ('rotometro-original', '1.0', 114, 'Su vehiculo tiene pegada una calcomania con cuatro caballitos corriendo o que diga turbo?'),
  ('rotometro-original', '1.0', 115, 'Compra helados Panda, especialmente el sshocopanda?'),
  ('rotometro-original', '1.0', 116, 'Va hasta el water con el celular en la mano para demostrarle a todo el mundo que usted es importante?'),
  ('rotometro-original', '1.0', 117, 'Usa (para hombres) pulsera de oro? O anillo del mismo material u otro con alguna piedra?'),
  ('rotometro-original', '1.0', 118, 'Le pregunta a su hijo/a de dos o mas anos"tenis pisshi" para ver si se le debe cambiar el panal?'),
  ('rotometro-original', '1.0', 119, 'Se rasca las bolas en publico o en una reuniony se hace el huevon o lo ace a traves del bolsillo del pantalon para que"no se note"?'),
  ('rotometro-original', '1.0', 120, 'Tiene su auto alguna calcomania de sshile oalgun otro pais para darselas de descendiente de extranjero?'),
  ('rotometro-original', '1.0', 121, 'Si ha tenido la suerte de salir del pais, te hatraido cuanta calcomania encuentra de universidades extranjeras(preferentemente harvard o ucla) y se las coloca al auto para mandarse laparte?'),
  ('rotometro-original', '1.0', 122, 'Se corta las unas en publico?'),
  ('rotometro-original', '1.0', 123, 'Disfruta de oir el clic del corta unas (enpublico)y adivinar a quien le caera la una voladora?'),
  ('rotometro-original', '1.0', 124, 'Solo para mujeres: Le gusta pintarse las unasde los pies (preferentemente de rojo) y cree que se ve chic?'),
  ('rotometro-original', '1.0', 125, 'Usa (mujer)algun tipo de peto y sin darse cuentade lo excedida de peso que esta, le queda un rollo colgando en el pantalon?'),
  ('rotometro-original', '1.0', 126, 'Tiene alguna funda o diente de oro?'),
  ('rotometro-original', '1.0', 127, 'Le falta alguno y no se lo ha arreglado y al reirse se le ve la pieza faltante?'),
  ('rotometro-original', '1.0', 128, 'Despues de comer empieza a chupetear paratratar de sacarse algun resto de comida que le ha quedado entre los dientes?'),
  ('rotometro-original', '1.0', 129, 'Cuando entra a un comedor o sala donde la genteesta almorzando, dice provessho?'),
  ('rotometro-original', '1.0', 130, 'En la epoca veraniega dice que "hace mussshacalor"?'),
  ('rotometro-original', '1.0', 131, 'Escucha la radio Corazon?'),
  ('rotometro-original', '1.0', 132, 'Cuando concurre a algun restaurant donde sepaga una cuota y se puede comer todo lo que desee, se llena platos como paracamionero y vuelve por mas y mas y cuando sale del restaurant dice "quedecon la guata para"...'),
  ('rotometro-original', '1.0', 133, 'En los matrimonios que lo invitan, come y toma como degenerado para recuperar la plata que gasto en el regalo?'),
  ('rotometro-original', '1.0', 134, 'Envio regalo?'),
  ('rotometro-original', '1.0', 135, 'Usa sshalas para que no se le caldeen las patas?'),
  ('rotometro-original', '1.0', 136, 'En vez de decir hora de almuerzo Ud. dice voy a colassion?'),
  ('rotometro-original', '1.0', 137, 'Se "gana" usted en algun lado cuando llega a algun lugar?'),
  ('rotometro-original', '1.0', 138, 'Cuando usted compra algun articulo electronico por ejemplo un televisor, dice "me saque una tele".'),
  ('rotometro-original', '1.0', 139, 'Cuanto usted invita a alguien a comer algo, le pregunta "? vamos a servirnos algo".'),
  ('rotometro-original', '1.0', 140, 'Pone algun tipo de estos elementos en su living: adornitos de vidrio pintado, chucherias de bronce o muebles de felpa?'),
  ('rotometro-original', '1.0', 141, 'Su perra se llama reina o pelusa o su perro sultan?'),
  ('rotometro-original', '1.0', 142, 'Se le ocurrio ponerle a su perro Casshupin?'),
  ('rotometro-original', '1.0', 143, 'Se corto la cola a su perro quiltro para que seviera mas fino?'),
  ('rotometro-original', '1.0', 144, 'Tiene un quiltro que cuando le preguntan por laraza Ud. dice que es "policial"?'),
  ('rotometro-original', '1.0', 145, 'Cuando va al bano de su casa, luego de haberobrado, ?tira los papeles usados al papelero?'),
  ('rotometro-original', '1.0', 146, 'Cuando esta en la oficina se saca los zapatos para ventilar las "Patitas"'),
  ('rotometro-original', '1.0', 147, 'Hace ruidos con la garganta al limpierse susvias respiratorias que estan con "mocos".'),
  ('rotometro-original', '1.0', 148, 'Cuando va al baño en la oficina, se saca lospuntos negros de la cara?? o espinillas ??.'),
  ('rotometro-original', '1.0', 149, 'Mantiene en su oficina un frasco de coloniapara mantenerse siempre fresco y perfumado ??'),
  ('rotometro-original', '1.0', 150, 'Cuando tiene sed en su casa, toma directamentedel jarro familiar.');

delete from questions where test_slug = 'rotometro-2' and test_version = '2.0';
insert into questions (test_slug, test_version, number, text) values
  ('rotometro-2', '2.0', 1, 'Escuchas música con tu celular sin audífonos en lugares públicos?'),
  ('rotometro-2', '2.0', 2, 'Evades el pago en el transporte público, pero para criticarlo eres el primero?'),
  ('rotometro-2', '2.0', 3, 'Sigues al repartidor en el mapa como si fuera final de campeonato?'),
  ('rotometro-2', '2.0', 4, 'Usas "mejores amigos" para contar lo que te pasa?'),
  ('rotometro-2', '2.0', 5, 'Publicas frases filosóficas de reflexión de baño público?'),
  ('rotometro-2', '2.0', 6, 'Consumes OnlyFans o Arsmate?'),
  ('rotometro-2', '2.0', 7, 'Publicas más de una historia al día?'),
  ('rotometro-2', '2.0', 8, 'Has ido en pijama a buscar un delivery?'),
  ('rotometro-2', '2.0', 9, 'Tienes una colección de bolsas plásticas en tu casa que solo aumenta?'),
  ('rotometro-2', '2.0', 10, 'Usas papel higiénico como servilleta?'),
  ('rotometro-2', '2.0', 11, 'Usas toalla nova como papel higiénico?'),
  ('rotometro-2', '2.0', 12, 'Has usado calcetines viejos, diario u otro recurso de emergencia en el baño?'),
  ('rotometro-2', '2.0', 13, 'Pones reclamos en el delivery buscando ganar una compensación, cuando sabes que el pedido llegó bien?'),
  ('rotometro-2', '2.0', 14, 'Te gusta la farándula?'),
  ('rotometro-2', '2.0', 15, 'Has dejado basura en la micro, plaza, playa o estadio?'),
  ('rotometro-2', '2.0', 16, 'Has comido sopaipillas, completo o empanada en transporte público dejando olor a todo el carro?'),
  ('rotometro-2', '2.0', 17, 'Cuando ves una emergencia en la calle, eres de los que graban en lugar de ayudar?'),
  ('rotometro-2', '2.0', 18, 'Has tomado bebida directo de la botella familiar y después te haces el hueón?'),
  ('rotometro-2', '2.0', 19, 'Sigues cuentas de copuchas?'),
  ('rotometro-2', '2.0', 20, 'Compartes funas sin leerlas?'),
  ('rotometro-2', '2.0', 21, 'Peleas con otras personas por redes sociales?'),
  ('rotometro-2', '2.0', 22, 'Regalas alcohol para los cumpleaños?'),
  ('rotometro-2', '2.0', 23, 'Si sales con más gente a comer o tomar, esperas a pagar al final para ver si zafaste?'),
  ('rotometro-2', '2.0', 24, 'Eres de los que dice "te transfiero" y jamás lo haces?'),
  ('rotometro-2', '2.0', 25, 'Dices "son cinco minutitos" dejando el auto bloqueando y cagándose en el resto?'),
  ('rotometro-2', '2.0', 26, 'Eres de los que toca la bocina al segundo exacto en que cambia la luz?'),
  ('rotometro-2', '2.0', 27, 'Tiras basura o no recoges la caca de tu perro cuando nadie te ve?'),
  ('rotometro-2', '2.0', 28, 'Te gusta ir con música fuerte en el auto para que todos escuchen?'),
  ('rotometro-2', '2.0', 29, 'Encuentras que los autos enchulados con luces se ven bien?'),
  ('rotometro-2', '2.0', 30, 'Dejas el carro del supermercado en cualquier parte del estacionamiento?'),
  ('rotometro-2', '2.0', 31, 'Usas el estacionamiento de visitas de tu edificio como si fuera tuyo?'),
  ('rotometro-2', '2.0', 32, 'Eres de los que usa el carro del edificio y no lo devuelve?'),
  ('rotometro-2', '2.0', 33, 'Has dejado pelos pegados en el jabón?'),
  ('rotometro-2', '2.0', 34, 'Crees que el perfume, desodorante o champú seco reemplaza la ducha?'),
  ('rotometro-2', '2.0', 35, 'Cuando sientes olor a axila, te hueles disimuladamente para ver si eres tú?'),
  ('rotometro-2', '2.0', 36, 'Picoteas papas fritas de otro plato o mesa "pa que no se pierdan"?'),
  ('rotometro-2', '2.0', 37, 'Eres de los que pregunta "a ver cuál es tu nombre" cuando pones un reclamo?'),
  ('rotometro-2', '2.0', 38, 'Si llevas algo a un asado y no se abrió, te lo llevas de vuelta sin que te vean?'),
  ('rotometro-2', '2.0', 39, 'Has rellenado una botella de destilado bueno con uno penca?'),
  ('rotometro-2', '2.0', 40, 'Cuando te invitan a almorzar, te comes hasta el último grano de arroz, porque "es gratis"?'),
  ('rotometro-2', '2.0', 41, 'Compras poleras de fútbol o remedios en las ferias?'),
  ('rotometro-2', '2.0', 42, 'Te gusta ver los videos del tío René?'),
  ('rotometro-2', '2.0', 43, 'Te gusta ver las fiscalizaciones del matinal?'),
  ('rotometro-2', '2.0', 44, 'Si vas a un tenedor libre, comes hasta "salir ganando"?'),
  ('rotometro-2', '2.0', 45, 'Te subes al metro antes de que la gente termine de bajar?'),
  ('rotometro-2', '2.0', 46, 'Le pones Coca-Cola al vino tinto?'),
  ('rotometro-2', '2.0', 47, 'Consideras que la TV chilena es seria?'),
  ('rotometro-2', '2.0', 48, 'Te gusta el fanshop?'),
  ('rotometro-2', '2.0', 49, 'Te tiras peos en lugares públicos?'),
  ('rotometro-2', '2.0', 50, 'Te inspira Sammis Reyes?');

delete from questions where test_slug = 'cuicometro' and test_version = '1.0';
insert into questions (test_slug, test_version, number, text) values
  ('cuicometro', '1.0', 1, 'Le has preguntado a alguien de qué colegio salió?'),
  ('cuicometro', '1.0', 2, 'Cuesta pronunciar tu apellido?'),
  ('cuicometro', '1.0', 3, 'Usas palabras en inglés innecesariamente?'),
  ('cuicometro', '1.0', 4, 'Te gusta dar consejos cuando nadie te los ha pedido?'),
  ('cuicometro', '1.0', 5, 'Consideras que tu viaje a Australia, a juntarte con chilenos, te cambió la vida?'),
  ('cuicometro', '1.0', 6, 'Conoces más de 10 países pero no conoces todo Chile?'),
  ('cuicometro', '1.0', 7, 'Piensas que el pobre es pobre porque es flojo?'),
  ('cuicometro', '1.0', 8, 'Crees que el golf es un deporte?'),
  ('cuicometro', '1.0', 9, 'Has entrado a una pega por pituto?'),
  ('cuicometro', '1.0', 10, 'Dices "estoy pobre" a la vuelta de unas vacaciones?'),
  ('cuicometro', '1.0', 11, 'Has ido a esquiar y lo cuentas como panorama normal de invierno?'),
  ('cuicometro', '1.0', 12, 'Consideras que Maitencillo se puso flaite?'),
  ('cuicometro', '1.0', 13, 'Tienes "picás" de platos de más de 20 lucas?'),
  ('cuicometro', '1.0', 14, 'Tienes o has tenido empleada doméstica?'),
  ('cuicometro', '1.0', 15, 'Te has puesto un chaleco cruzado sobre los hombros?'),
  ('cuicometro', '1.0', 16, 'Usas ropa Patagonia o North Face?'),
  ('cuicometro', '1.0', 17, 'Cuando regresas de un viaje, comparas todo lo que ves con el lugar al que fuiste?'),
  ('cuicometro', '1.0', 18, 'Dices que algo "queda lejos" si no está en tu radio habitual de tres comunas?'),
  ('cuicometro', '1.0', 19, 'Consideras flaites a los ñuñoínos?'),
  ('cuicometro', '1.0', 20, 'Conoces Ñuñoa?'),
  ('cuicometro', '1.0', 21, 'Conoces a alguien, o tú, te has metido con tu primo/a?'),
  ('cuicometro', '1.0', 22, 'Dices "la señora que nos ayuda" por no decir nana?'),
  ('cuicometro', '1.0', 23, 'Has dicho "es como de la familia" sobre alguien que trabaja en tu casa?'),
  ('cuicometro', '1.0', 24, 'Dices "hoy me tocó limpiar" como si fuera una hazaña?'),
  ('cuicometro', '1.0', 25, 'Usas el "no hay dónde estacionar" como razón para no ir a un lugar?'),
  ('cuicometro', '1.0', 26, 'Dices "heavy" para todo lo que es levemente intenso?'),
  ('cuicometro', '1.0', 27, 'Vas menos de una vez al año al centro de tu ciudad?'),
  ('cuicometro', '1.0', 28, 'Consideras que Rancagua, Talca y Curicó son el sur?'),
  ('cuicometro', '1.0', 29, 'Hablas "del lago" como si el lago viniera especificado por defecto?'),
  ('cuicometro', '1.0', 30, 'Te gusta el programa de política Sin Filtros?'),
  ('cuicometro', '1.0', 31, 'Has dicho "no fue pituto, fue dato"?'),
  ('cuicometro', '1.0', 32, 'Dices "no somos cuicos" porque conoces a gente más cuica que tú?'),
  ('cuicometro', '1.0', 33, 'Has usado el concepto "se desperfiló"?'),
  ('cuicometro', '1.0', 34, 'Consideras ordinaria a la gente que dice "provecho"?'),
  ('cuicometro', '1.0', 35, 'Te cae bien la Paty Maldonado o la Raquel Argandoña?'),
  ('cuicometro', '1.0', 36, 'Consideras que la familia de Joaquín Lavín es honesta?'),
  ('cuicometro', '1.0', 37, 'Vas a misa?'),
  ('cuicometro', '1.0', 38, 'Te espantas cuando alguien dice "la calor" o "la mar"?'),
  ('cuicometro', '1.0', 39, 'Confundes ocasionalmente algo popular tildándolo de flaite?'),
  ('cuicometro', '1.0', 40, 'Ante los escándalos de corrupción, eres de los que dicen "dejemos que actúe la justicia"?'),
  ('cuicometro', '1.0', 41, 'Consideras que El Mercurio se ha puesto zurdo?'),
  ('cuicometro', '1.0', 42, 'Te refieres a la Universidad Católica como "la Cato"?'),
  ('cuicometro', '1.0', 43, 'Ganas discusiones hablando más fuerte?'),
  ('cuicometro', '1.0', 44, 'Piensas que viajar por Sudamérica no es un viaje?'),
  ('cuicometro', '1.0', 45, 'Crees que RN no es de derecha?'),
  ('cuicometro', '1.0', 46, 'Si escuchas una canción de misa, te pones a cantarla?'),
  ('cuicometro', '1.0', 47, 'Te gusta subir cerros?'),
  ('cuicometro', '1.0', 48, 'Cuando te invitan a algún lugar, preguntas quiénes van?'),
  ('cuicometro', '1.0', 49, 'Llamas "ingenería" a la carrera de ingeniería comercial?'),
  ('cuicometro', '1.0', 50, 'Has ido al Interescolar?');

delete from questions where test_slug = 'chantometro' and test_version = '1.0';
insert into questions (test_slug, test_version, number, text) values
  ('chantometro', '1.0', 1, '¿Pusiste "inglés avanzado" en el currículum y tu mayor logro es entender los memes?'),
  ('chantometro', '1.0', 2, '¿Tu "Excel avanzado" consiste en pintar celdas de colores?'),
  ('chantometro', '1.0', 3, '¿Dijiste en una entrevista que tu mayor defecto es "ser demasiado perfeccionista"?'),
  ('chantometro', '1.0', 4, '¿Consideras a Kaminski un emprendedor?'),
  ('chantometro', '1.0', 5, '¿Te gustaría trabajar en una municipalidad?'),
  ('chantometro', '1.0', 6, 'Para zafar, ¿algún familiar tuyo "ha muerto" más de una vez?'),
  ('chantometro', '1.0', 7, '¿Has dejado el mouse moviéndose solo para aparecer "conectado" en teletrabajo?'),
  ('chantometro', '1.0', 8, '¿Eres parte del selecto grupo que viajó al extranjero estando con licencia médica?'),
  ('chantometro', '1.0', 9, '¿Has dicho "lo estamos viendo" sobre algo que nadie está viendo?'),
  ('chantometro', '1.0', 10, '¿Crees que el Huevo Fuenzalida "la hizo bien" registrando marcas ajenas?'),
  ('chantometro', '1.0', 11, '¿Te han tenido que "recordar" una transferencia que habías quedado de hacer?'),
  ('chantometro', '1.0', 12, 'Si tuvieras un problema legal, ¿te gustaría que te defendiera Lucho Hermosilla?'),
  ('chantometro', '1.0', 13, '¿Consideras que Emeterio Ureta debería tener más espacio en la TV?'),
  ('chantometro', '1.0', 14, '¿Has ido estratégicamente al baño cuando llegó la cuenta?'),
  ('chantometro', '1.0', 15, '¿Crees que Mauricio Israel es honesto?'),
  ('chantometro', '1.0', 16, '¿Pediste plata prestada para pagarle a otro al que le debías, y lo llamaste "gestión financiera"?'),
  ('chantometro', '1.0', 17, '¿Consideras que la justicia es justa con los delitos financieros?'),
  ('chantometro', '1.0', 18, '¿Crees que Tonka Tomicic debía volver a la TV?'),
  ('chantometro', '1.0', 19, '¿Publicaste "se vende por viaje" sin tener pasaje ni intención?'),
  ('chantometro', '1.0', 20, '¿Has boleteado por una "asesoría verbal" de la que no queda ni un audio?'),
  ('chantometro', '1.0', 21, '¿Le creíste, aunque sea un 1%, a Cote López?'),
  ('chantometro', '1.0', 22, '¿Has dicho "se me murió el celular" con batería suficiente?'),
  ('chantometro', '1.0', 23, '¿Has cortado una llamada diciendo "aló, aló, aló…" y fingiendo no escuchar?'),
  ('chantometro', '1.0', 24, '¿Has jurado en vano por algún familiar?'),
  ('chantometro', '1.0', 25, '¿Ofreciste ayudar en una mudanza y ese día "te surgió una emergencia"?'),
  ('chantometro', '1.0', 26, '¿Has dicho "cuenta conmigo para lo que necesites" rogando que no necesite nada?'),
  ('chantometro', '1.0', 27, '¿Pagas un gimnasio al que no vas, pero dices "estoy entrenando"?'),
  ('chantometro', '1.0', 28, '¿Llegas a las juntas con las manos vacías y una sonrisa?'),
  ('chantometro', '1.0', 29, '¿Has "maquillado" la verdad en aplicaciones de citas?'),
  ('chantometro', '1.0', 30, '¿Has dicho "te llamo" con la tranquilidad de quien sabe que jamás lo hará?'),
  ('chantometro', '1.0', 31, '¿Te presentas como "emprendedor" cuando estás desempleado?'),
  ('chantometro', '1.0', 32, '¿Has pensado en vender cursos online?'),
  ('chantometro', '1.0', 33, '¿Enseñas a invertir después de haber perdido tus ahorros invirtiendo?'),
  ('chantometro', '1.0', 34, '¿Has escrito "voy saliendo" cuando te faltaban más de 10 minutos para salir?'),
  ('chantometro', '1.0', 35, '¿Has dicho "tengo un proyecto que te puede interesar" y era un negocio piramidal?'),
  ('chantometro', '1.0', 36, '¿Eres de los que hablan constantemente de negocios y de plata?'),
  ('chantometro', '1.0', 37, '¿Te has "retocado" antes de subir o mandar alguna foto?'),
  ('chantometro', '1.0', 38, '¿Has emitido boletas ideológicamente falsas?'),
  ('chantometro', '1.0', 39, '¿Le pediste algo a una inteligencia artificial y después dijiste "me costó harto hacerlo"?'),
  ('chantometro', '1.0', 40, '¿Has dicho "estamos conversando con inversionistas" y el inversionista era tu tío?'),
  ('chantometro', '1.0', 41, '¿Usas el concepto "optimización de impuestos"?'),
  ('chantometro', '1.0', 42, '¿Has dicho "¿usted sabe quién soy yo?" sin ser absolutamente nadie?'),
  ('chantometro', '1.0', 43, '¿Te estacionaste en el espacio para personas con discapacidad y te bajaste cojeando, por si acaso?'),
  ('chantometro', '1.0', 44, '¿Has inventado una historia para que no te saquen un parte?'),
  ('chantometro', '1.0', 45, '¿Has preguntado "¿y sin boleta en cuánto queda?"?'),
  ('chantometro', '1.0', 46, '¿Reclamas "con mis impuestos" sabiendo que debes más que Don Ramón?'),
  ('chantometro', '1.0', 47, '¿Crees que Sammis Reyes es un genio de los negocios?'),
  ('chantometro', '1.0', 48, '¿Estás de acuerdo con que exista Capitán Yáber?'),
  ('chantometro', '1.0', 49, '¿Has devuelto un artículo por "falla" sabiendo que tú lo hiciste fallar?'),
  ('chantometro', '1.0', 50, '¿Adulteraste tests de COVID?');

notify pgrst, 'reload schema';
